### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by KerronKing** [KerronKing/Weather-App-JS#2]

**Comment by rmauritsson** [comment]
Nice Interface, try to fix the issue where inputting a city /country with a capital letter causes an error.

**Comment by rociac** [comment]
The project is looking nice! Just fix the lowercasing issue and try to implement a toggle instead of a checkbox as required in the project.

**Comment by RoyNyaga** [comment]
everything looks nice to me just the error that pops up when hosted on git.
